# Generated by Django 4.0 on 2021-12-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_appsettings_wabpages_wabapps_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='WABPagesTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.BinaryField(blank=True, null=True)),
                ('js_content', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WABPagesTemplates',
            },
        ),
        migrations.AlterModelTable(
            name='appsettings',
            table='AppSettings',
        ),
    ]
