# Generated by Django 4.0 on 2022-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_wabpagestemplates_alter_appsettings_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wabpages',
            name='html_content',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='wabpages',
            name='js_content',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='wabpagestemplates',
            name='html_content',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='wabpagestemplates',
            name='js_content',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
